services:
  - type: web
    name: projectmanagement-client
    runtime: static
    buildCommand: cd ProjectManagement.Client && npm install && npm run build
    staticPublishPath: ProjectManagement.Client/dist/project-management.client/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
